#pragma once
#include <mpi.h>
#include <iostream>
#include <string>
void test1(MPI_Comm);
void test2(MPI_Comm);
void test3(MPI_Comm);
void test4(MPI_Comm);
void test5(MPI_Comm);
void test6(MPI_Comm);
void test7(MPI_Comm);
void test8(MPI_Comm);
void test9(MPI_Comm);